"use client";

import { motion } from "framer-motion";
import { duration, ease, fadeUp, staggerContainer } from "@/lib/motion";
import { PageShell } from "@/components/PageShell";
import Link from "next/link";

const SECTIONS = [
  {
    id: "overview",
    title: "Overview",
    content: [
      {
        heading: "What is ADW?",
        text: "Autonomous Developer Workspace (ADW) is an enterprise-grade AI-powered development platform that transforms natural language descriptions into production-ready code. Built with cutting-edge AI technology, ADW automates the entire software development lifecycle—from planning and coding to testing, review, and deployment.",
      },
      {
        heading: "Our Mission",
        text: "To revolutionize software development by providing intelligent automation tools that enhance developer productivity and code quality. We believe in building technology that empowers teams to focus on innovation rather than repetitive tasks.",
      },
      {
        heading: "Technology Stack",
        text: "Built with Next.js 14, React 18, Python 3.11+, FastAPI, Firebase, Groq AI (Llama 3.3 70B), and deployed on enterprise cloud infrastructure with 99.9% uptime SLA.",
      },
    ],
  },
  {
    id: "features",
    title: "Core Features",
    content: [
      {
        heading: "AI Task Planning",
        text: "Automatically breaks down complex project descriptions into manageable, dependency-aware tasks using advanced language models with context-aware analysis.",
      },
      {
        heading: "Multi-Agent System",
        text: "Three specialized AI agents work in sequence: Code Generator produces clean, maintainable code; Test Generator creates comprehensive test suites; Code Reviewer ensures quality, security, and best practices compliance.",
      },
      {
        heading: "Real-Time Collaboration",
        text: "WebSocket-powered live updates provide instant synchronization across teams. Monitor task progress, deployment status, and code generation in real-time with sub-second latency.",
      },
      {
        heading: "CI/CD Pipeline",
        text: "Automated testing, building, and deployment pipeline with support for major platforms including Vercel, GitHub Pages, and custom deployment targets.",
      },
      {
        heading: "Code Editor",
        text: "Monaco-powered editor (same engine as Visual Studio Code) with syntax highlighting, IntelliSense, version control integration, and AI-assisted code completion.",
      },
      {
        heading: "Observability Dashboard",
        text: "Comprehensive monitoring and analytics with detailed logs, performance metrics, agent activity tracking, error reporting, and audit trails.",
      },
    ],
  },
  {
    id: "legal",
    title: "Legal & Compliance",
    content: [
      {
        heading: "Proprietary License",
        text: "ADW is proprietary software owned and operated by ADW Technologies. All rights reserved. Unauthorized copying, distribution, or modification of this software is strictly prohibited and may result in legal action.",
      },
      {
        heading: "Intellectual Property",
        text: "All code, algorithms, designs, documentation, and related materials are the exclusive property of ADW Technologies. Users are granted a limited, non-transferable license to use the software as specified in their subscription agreement.",
      },
      {
        heading: "Data Privacy & GDPR Compliance",
        text: "We are fully compliant with GDPR, CCPA, and other international data protection regulations. User data is stored securely in Firebase Firestore with AES-256 encryption. We do not sell, rent, or share personal information with third parties except as required by law.",
      },
      {
        heading: "AI-Generated Code Warranty",
        text: "Code generated by ADW is provided 'as-is' without warranty of any kind, express or implied. Users are solely responsible for reviewing, testing, and validating all AI-generated code before production deployment. ADW Technologies assumes no liability for code quality or functionality.",
      },
      {
        heading: "Third-Party Services",
        text: "ADW integrates with Groq AI for language model inference and Firebase for authentication and data storage. Usage is subject to their respective terms of service and privacy policies. We maintain service level agreements with all third-party providers.",
      },
      {
        heading: "Limitation of Liability",
        text: "ADW Technologies shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from the use or inability to use the software. Total liability shall not exceed the amount paid by the user in the twelve months preceding the claim.",
      },
    ],
  },
  {
    id: "security",
    title: "Security & Privacy",
    content: [
      {
        heading: "Authentication & Authorization",
        text: "Firebase Authentication with support for email/password, Google OAuth, and enterprise SSO providers. All sessions are secured with JWT tokens with automatic expiration and refresh mechanisms. Multi-factor authentication (MFA) available for enterprise accounts.",
      },
      {
        heading: "Data Encryption",
        text: "All data in transit is encrypted using TLS 1.3 with perfect forward secrecy. Data at rest is encrypted using AES-256 encryption with Firebase's built-in security infrastructure. Encryption keys are managed through Google Cloud KMS.",
      },
      {
        heading: "Access Control",
        text: "Role-based access control (RBAC) with granular permissions for user, admin, and custom roles. Users can only access their own projects and data unless explicitly granted permission. All access attempts are logged for audit purposes.",
      },
      {
        heading: "Code Security Scanning",
        text: "AI-generated code is automatically scanned for common security vulnerabilities including SQL injection, XSS, CSRF, insecure deserialization, and resource leaks. OWASP Top 10 compliance checks are performed on all generated code.",
      },
      {
        heading: "Audit Logs & Compliance",
        text: "Comprehensive audit logging tracks all user actions, admin operations, and system events. Logs are retained for 90 days and available for export. SOC 2 Type II compliance in progress.",
      },
      {
        heading: "Incident Response",
        text: "24/7 security monitoring with automated threat detection. Incident response team available for enterprise customers. Security vulnerabilities can be reported to security@adw.com with guaranteed response within 24 hours.",
      },
    ],
  },
  {
    id: "terms",
    title: "Terms of Service",
    content: [
      {
        heading: "Acceptance of Terms",
        text: "By accessing and using ADW, you accept and agree to be bound by these terms and conditions. If you do not agree to these terms, you must immediately cease using the service. Continued use constitutes acceptance of any modifications to these terms.",
      },
      {
        heading: "User Responsibilities",
        text: "Users are responsible for maintaining the confidentiality of their account credentials, all activities conducted under their account, and compliance with all applicable laws and regulations. Users must notify ADW immediately of any unauthorized access or security breach.",
      },
      {
        heading: "Acceptable Use Policy",
        text: "Users must not use ADW to generate malicious code, violate intellectual property rights, engage in illegal activities, or circumvent security measures. We reserve the right to immediately terminate accounts that violate these terms without refund.",
      },
      {
        heading: "Service Availability & SLA",
        text: "We strive for 99.9% uptime with scheduled maintenance windows announced 48 hours in advance. Service level agreements (SLA) are available for enterprise customers with guaranteed uptime and priority support.",
      },
      {
        heading: "Modifications to Terms",
        text: "We reserve the right to modify these terms at any time. Users will be notified of material changes via email 30 days in advance. Continued use of the service after modifications constitutes acceptance of the updated terms.",
      },
      {
        heading: "Termination & Suspension",
        text: "We may terminate or suspend access immediately, without prior notice, for conduct that violates these terms, is harmful to other users, or poses a security risk. Upon termination, users have 30 days to export their data before permanent deletion.",
      },
      {
        heading: "Dispute Resolution",
        text: "Any disputes arising from these terms shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association. Users waive the right to participate in class action lawsuits.",
      },
    ],
  },
  {
    id: "attribution",
    title: "Technology & Attribution",
    content: [
      {
        heading: "AI Technology",
        text: "Powered by Groq AI infrastructure and Meta's Llama 3.3 70B language model. We maintain enterprise agreements with all AI service providers to ensure reliability and data privacy.",
      },
      {
        heading: "Third-Party Libraries",
        text: "Built with React, Next.js, FastAPI, Framer Motion, Monaco Editor, React Flow, and other industry-standard libraries. All dependencies are regularly audited for security vulnerabilities.",
      },
      {
        heading: "Infrastructure",
        text: "Hosted on Google Cloud Platform with multi-region redundancy. Database services provided by Firebase with automatic backups and point-in-time recovery.",
      },
      {
        heading: "Compliance Certifications",
        text: "GDPR compliant, CCPA compliant, SOC 2 Type II in progress. Regular third-party security audits conducted annually.",
      },
    ],
  },
  {
    id: "contact",
    title: "Contact & Support",
    content: [
      {
        heading: "Technical Support",
        text: "Email: support@adw.com | Response time: 24 hours (standard), 4 hours (enterprise)",
      },
      {
        heading: "Sales & Partnerships",
        text: "For enterprise inquiries, partnership opportunities, or custom solutions: sales@adw.com",
      },
      {
        heading: "Security Issues",
        text: "Report security vulnerabilities to: security@adw.com | Guaranteed response within 24 hours",
      },
      {
        heading: "Legal & Compliance",
        text: "For legal inquiries, GDPR requests, or compliance questions: legal@adw.com",
      },
      {
        heading: "Documentation",
        text: "Comprehensive API documentation, integration guides, and best practices available at docs.adw.com",
      },
      {
        heading: "Business Address",
        text: "ADW Technologies Inc. | 123 Innovation Drive, San Francisco, CA 94105, United States",
      },
    ],
  },
];

const STATS = [
  { label: "Proprietary", value: "Licensed" },
  { label: "AI Agents", value: "3" },
  { label: "Uptime SLA", value: "99.9%" },
  { label: "Version", value: "1.0.0" },
];

export default function AboutPage() {
  return (
    <PageShell>
      {/* Ambient background */}
      <div className="pointer-events-none fixed inset-0 overflow-hidden" aria-hidden>
        <div
          className="absolute top-0 left-1/4 h-[500px] w-[500px] rounded-full opacity-10"
          style={{ background: "radial-gradient(circle, #6366f1 0%, transparent 70%)", filter: "blur(100px)" }}
        />
        <div
          className="absolute bottom-0 right-1/4 h-[400px] w-[400px] rounded-full opacity-10"
          style={{ background: "radial-gradient(circle, #8b5cf6 0%, transparent 70%)", filter: "blur(100px)" }}
        />
      </div>

      {/* Header */}
      <header className="app-topbar relative flex h-20 shrink-0 items-center justify-between px-8 border-b border-white/5">
        <div>
          <h1 className="app-title text-2xl font-semibold text-gray-100">About ADW</h1>
          <p className="text-sm text-gray-500 mt-0.5">Legal, Security, and Documentation</p>
        </div>
        <Link
          href="/home"
          className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-gray-300 transition-colors hover:bg-white/10"
        >
          <svg viewBox="0 0 16 16" fill="currentColor" className="h-3.5 w-3.5">
            <path fillRule="evenodd" d="M9.78 12.78a.75.75 0 01-1.06 0L4.47 8.53a.75.75 0 010-1.06l4.25-4.25a.75.75 0 011.06 1.06L6.06 8l3.72 3.72a.75.75 0 010 1.06z" clipRule="evenodd" />
          </svg>
          Back to Home
        </Link>
      </header>

      <main className="relative flex-1 overflow-y-auto px-8 py-10">
        {/* Hero Section */}
        <motion.div
          className="mb-12 text-center"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: duration.slow, ease: ease.enter }}
        >
          <div className="mb-6 flex justify-center">
            <motion.div
              className="relative flex h-20 w-20 items-center justify-center"
              whileHover={{ scale: 1.05 }}
              transition={{ duration: 0.2 }}
            >
              <motion.div
                className="absolute inset-0 rounded-[20px] bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500 opacity-90"
                animate={{ rotate: [0, 360] }}
                transition={{ duration: 8, repeat: Infinity, ease: "linear" }}
              />
              <div className="absolute inset-0 rounded-[20px] bg-gradient-to-br from-indigo-400 via-purple-400 to-pink-400 blur-xl opacity-40" />
              
              <div className="relative z-10 flex h-full w-full items-center justify-center rounded-[20px] bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-600">
                <svg viewBox="0 0 24 24" fill="none" className="h-10 w-10 text-white drop-shadow-lg">
                  <motion.circle cx="12" cy="12" r="2.5" fill="currentColor" animate={{ scale: [1, 1.2, 1], opacity: [1, 0.8, 1] }} transition={{ duration: 2, repeat: Infinity }} />
                  <motion.circle cx="6" cy="6" r="1.5" fill="currentColor" opacity="0.9" animate={{ scale: [1, 1.15, 1] }} transition={{ duration: 2, repeat: Infinity, delay: 0.2 }} />
                  <motion.circle cx="18" cy="6" r="1.5" fill="currentColor" opacity="0.9" animate={{ scale: [1, 1.15, 1] }} transition={{ duration: 2, repeat: Infinity, delay: 0.4 }} />
                  <motion.circle cx="6" cy="18" r="1.5" fill="currentColor" opacity="0.9" animate={{ scale: [1, 1.15, 1] }} transition={{ duration: 2, repeat: Infinity, delay: 0.6 }} />
                  <motion.circle cx="18" cy="18" r="1.5" fill="currentColor" opacity="0.9" animate={{ scale: [1, 1.15, 1] }} transition={{ duration: 2, repeat: Infinity, delay: 0.8 }} />
                  <motion.line x1="6" y1="6" x2="12" y2="12" stroke="currentColor" strokeWidth="1.5" opacity="0.6" animate={{ opacity: [0.4, 0.8, 0.4] }} transition={{ duration: 2, repeat: Infinity, delay: 0.1 }} />
                  <motion.line x1="18" y1="6" x2="12" y2="12" stroke="currentColor" strokeWidth="1.5" opacity="0.6" animate={{ opacity: [0.4, 0.8, 0.4] }} transition={{ duration: 2, repeat: Infinity, delay: 0.3 }} />
                  <motion.line x1="6" y1="18" x2="12" y2="12" stroke="currentColor" strokeWidth="1.5" opacity="0.6" animate={{ opacity: [0.4, 0.8, 0.4] }} transition={{ duration: 2, repeat: Infinity, delay: 0.5 }} />
                  <motion.line x1="18" y1="18" x2="12" y2="12" stroke="currentColor" strokeWidth="1.5" opacity="0.6" animate={{ opacity: [0.4, 0.8, 0.4] }} transition={{ duration: 2, repeat: Infinity, delay: 0.7 }} />
                </svg>
              </div>
            </motion.div>
          </div>

          <h2 className="mb-3 text-4xl font-bold bg-gradient-to-r from-white via-gray-100 to-gray-300 bg-clip-text text-transparent">
            Autonomous Developer Workspace
          </h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto">
            Enterprise AI-Powered Development Platform
          </p>

          {/* Stats */}
          <motion.div
            className="mt-8 grid grid-cols-2 md:grid-cols-4 gap-4 max-w-3xl mx-auto"
            variants={staggerContainer}
            initial="hidden"
            animate="visible"
          >
            {STATS.map((stat) => (
              <motion.div
                key={stat.label}
                variants={fadeUp}
                className="rounded-2xl border border-white/10 bg-white/5 p-4 backdrop-blur-sm"
              >
                <div className="text-xl font-bold text-white">{stat.value}</div>
                <div className="text-xs text-gray-500 mt-1">{stat.label}</div>
              </motion.div>
            ))}
          </motion.div>
        </motion.div>

        {/* Content Sections */}
        <motion.div
          className="max-w-5xl mx-auto space-y-8"
          variants={staggerContainer}
          initial="hidden"
          animate="visible"
        >
          {SECTIONS.map((section) => (
            <motion.section
              key={section.id}
              variants={fadeUp}
              className="rounded-2xl border border-white/10 bg-gradient-to-br from-white/5 to-white/[0.02] p-8 backdrop-blur-sm"
            >
              <h3 className="text-2xl font-bold text-white mb-6">{section.title}</h3>

              <div className="space-y-6">
                {section.content.map((item, i) => (
                  <div key={i} className="border-l-2 border-indigo-500/30 pl-6">
                    <h4 className="text-lg font-semibold text-gray-200 mb-2">{item.heading}</h4>
                    <p className="text-sm text-gray-400 leading-relaxed">{item.text}</p>
                  </div>
                ))}
              </div>
            </motion.section>
          ))}
        </motion.div>

        {/* Footer */}
        <motion.footer
          className="mt-16 text-center pb-8"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5, duration: duration.slow }}
        >
          <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-6 py-3 backdrop-blur-sm">
            <span className="text-sm text-gray-400">Developed by</span>
            <span className="text-sm font-semibold text-indigo-400">ADW Technologies</span>
          </div>
          <p className="mt-4 text-xs text-gray-600">
            © 2025 ADW Technologies Inc. All rights reserved.
          </p>
        </motion.footer>
      </main>
    </PageShell>
  );
}
